meta_product_name: "Scribble"
meta_title: "Create and visualise your plot | Craft stories that work | Scribble "
meta_description: "The all-in-one toolkit for creating stories that work"
meta_image: "cover.png" # should exist in `app/assets/images/`
